/**
 * Pull requests.
 *
 * Trap 10: git and gh are spawned without a shell, and the body goes through
 * `--body-file`, because a shell mangles quotes, newlines, `|` and `>` (every PR body has
 * them). PatchPilot only ever opens DRAFT PRs; a human reviews and merges.
 */
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { redact } from "./sandbox.ts";
import type { Incident } from "../types.ts";

const MAX_ROOT_CAUSE = 72;

function oneLine(s: string): string {
  return String(s ?? "").replace(/\s+/g, " ").trim();
}

/** `fix: <root cause, at most 72 characters>`. */
export function buildPrTitle(inc: Incident): string {
  const rc = oneLine(inc.triage?.rootCause || inc.title);
  const short = rc.length > MAX_ROOT_CAUSE ? `${rc.slice(0, MAX_ROOT_CAUSE - 1).trimEnd()}…` : rc;
  return `fix: ${short}`;
}

const check = (ok: boolean | undefined) => (ok ? "[x]" : "[ ]");

export function buildPrBody(inc: Incident, opts: { inrPerUsd?: number } = {}): string {
  const t = inc.triage;
  const r = inc.reproduction;
  const final = [...inc.attempts].reverse().find((a) => a.ok);
  const review = inc.review;
  const lines: string[] = [];

  lines.push(`## Fixes ${inc.id} — ${inc.exceptionType}: ${oneLine(inc.exceptionValue)}`);
  lines.push(
    `_fingerprint \`${inc.fingerprint.slice(0, 12)}\`, ${inc.occurrences} occurrence${inc.occurrences === 1 ? "" : "s"}, first seen ${inc.firstSeen}_`
  );
  lines.push("");
  lines.push(`**Root cause:** ${oneLine(t?.rootCause ?? "unknown")}`);
  lines.push(`**Confidence:** triage ${t ? t.confidence.toFixed(2) : "n/a"} · review ${review ? review.confidence.toFixed(2) : "n/a"}`);
  if (review?.openQuestion) lines.push(`**Open question:** ${oneLine(review.openQuestion)}`);

  lines.push("", "### Evidence");
  for (const s of t?.suspects ?? []) {
    const range = s.lineStart ? ` (lines ${s.lineStart}-${s.lineEnd})` : "";
    lines.push(`- \`${s.file}${s.symbol ? `:${s.symbol}` : ""}\`${range}${s.reason ? ` — ${oneLine(s.reason)}` : ""}${s.score !== undefined ? ` (score ${s.score})` : ""}`);
  }
  const tx = inc.events.at(-1)?.transaction;
  if (tx && inc.exceptionType !== "ReportedBug") lines.push(`- Transaction: \`${tx}\``);
  if (inc.description) lines.push(`- Report: ${oneLine(inc.description)}`);

  lines.push("", "### Reproduction test");
  if (r) {
    lines.push(`\`${r.testFile}\` — **${oneLine(r.testName)}**`);
    lines.push(`Fails on the base branch${r.failureSummary ? `: ${oneLine(r.failureSummary).slice(0, 300)}` : "."}`);
    lines.push("Passes on this branch (see Verification). It was committed before the fix and locked (SHA-256).");
  }

  lines.push("", "### Change summary");
  if (final) {
    lines.push(`Changed ${final.files.map((f) => `\`${f}\``).join(", ")}: ${oneLine(final.text ?? t?.intendedBehavior ?? "")}`);
  }

  lines.push("", "### Verification");
  if (final) {
    lines.push(`- ${check(final.reproTest?.ok)} reproduction test: ${oneLine(final.reproTest?.summary ?? "").slice(0, 120)}`);
    lines.push(
      `- ${check(final.fullSuite?.ok)} full suite: ${final.fullSuite?.passed ?? 0} passed / ${final.fullSuite?.failed ?? 0} failed`
    );
    for (const h of final.hardChecks) lines.push(`- ${check(h.ok)} ${h.name}`);
  }
  if (review) {
    const outside = review.behaviorChangeOutsideCrashPath;
    lines.push(
      `- ${check(review.addressesRootCause && !outside)} independent critic: ${review.addressesRootCause ? "addresses the root cause" : "does NOT clearly address the root cause"}, ${
        outside ? `behavior change outside the crash path: ${typeof outside === "string" ? outside : "yes"}` : "no behavior change outside the crash path"
      }`
    );
  }

  lines.push("", "### What the agent did not do / risk notes");
  lines.push("- Did not touch test files, protected paths or secrets (guardrail-enforced in code, not by prompt).");
  if (inc.attempts.length > 1) lines.push(`- Needed ${inc.attempts.length} attempts; earlier ones were rejected and reverted.`);
  for (const risk of review?.risks ?? []) lines.push(`- ${oneLine(risk)}`);
  if (inc.guardrailBlocks.length > 0) {
    lines.push(`- ${inc.guardrailBlocks.length} unsafe action(s) were blocked during this run:`);
    for (const b of inc.guardrailBlocks.slice(0, 10)) lines.push(`  - ${b.stage}/${b.tool}: ${oneLine(b.reason)}`);
  }

  lines.push("", "### Provenance");
  const files = final?.files.length ?? 0;
  const inr = inc.usage.costInr.toFixed(2);
  const usd = inc.usage.costUsd.toFixed(4);
  lines.push(`Generated by PatchPilot run \`${inc.id}\` · ${files} file(s) changed · cost ₹${inr} ($${usd})${opts.inrPerUsd ? ` at ₹${opts.inrPerUsd}/$` : ""}`);
  lines.push("", "A human reviews and merges this PR — PatchPilot never merges its own patches.");
  return lines.join("\n");
}

function run(cmd: string, args: string[], cwd: string): { ok: boolean; out: string; err: string } {
  const res = spawnSync(cmd, args, {
    cwd,
    encoding: "utf8",
    shell: false,
    stdio: ["ignore", "pipe", "pipe"],
    env: { ...process.env, GIT_TERMINAL_PROMPT: "0", GH_PROMPT_DISABLED: "1" },
    timeout: 120_000,
    windowsHide: true,
  });
  if (res.error) return { ok: false, out: "", err: `${cmd} could not run: ${res.error.message}` };
  return { ok: res.status === 0, out: (res.stdout ?? "").trim(), err: (res.stderr ?? "").trim() };
}

/**
 * Pushes the branch and opens a draft PR. Returns `{ url }` or `{ error }`; never throws.
 * `base` is the branch to merge into (omitted → the repo's default branch).
 */
export function openDraftPr(
  dir: string,
  branch: string,
  title: string,
  body: string,
  base?: string
): { url?: string; error?: string } {
  const bodyFile = path.join(os.tmpdir(), `patchpilot-pr-${process.pid}-${Date.now()}.md`);
  try {
    fs.writeFileSync(bodyFile, body, "utf8");
    const push = run("git", ["push", "-u", "origin", branch], dir);
    if (!push.ok) return { error: `git push failed: ${redact(push.err || push.out)}` };
    const args = ["pr", "create", "--draft", "--title", title, "--body-file", bodyFile, "--head", branch];
    if (base && base !== "HEAD") args.push("--base", base);
    const pr = run("gh", args, dir);
    if (!pr.ok) return { error: `gh pr create failed: ${redact(pr.err || pr.out)}` };
    const url = pr.out.split(/\r?\n/).reverse().find((l) => /^https?:\/\//.test(l.trim()))?.trim();
    return url ? { url } : { error: `gh pr create gave no URL: ${redact(pr.out)}` };
  } catch (err) {
    return { error: redact(err instanceof Error ? err.message : String(err)) };
  } finally {
    fs.rmSync(bodyFile, { force: true });
  }
}
