/**
 * Build the standalone demo shop next to this repo, so the live demo has a real target.
 *
 * The shop is the same Express app as `demo-app/`, with the capture middleware bundled
 * inside it (`./sdk/…` instead of `../sdk/…`) and its own git history, so it can be pushed
 * to GitHub and receive real pull requests.
 *
 *   npm run demo:make-shop              # writes ../demo-shop
 *   npm run demo:make-shop -- <parent>  # writes <parent>/demo-shop (used by the tests)
 *
 * It refuses to touch an existing folder: deleting a repo someone made by hand is not
 * this script's business.
 */
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = path.resolve(HERE, "..");
const SHOP_NAME = "demo-shop";

const COPY_SKIP = new Set(["node_modules", ".git", ".patchpilot"]);

/** Recursive copy that skips node_modules/.git. */
function copyTree(from: string, to: string): void {
  fs.mkdirSync(to, { recursive: true });
  for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
    if (COPY_SKIP.has(entry.name)) continue;
    const src = path.join(from, entry.name);
    const dest = path.join(to, entry.name);
    if (entry.isDirectory()) copyTree(src, dest);
    else if (entry.isFile()) fs.copyFileSync(src, dest);
  }
}

function git(cwd: string, args: string[]): void {
  const res = spawnSync("git", ["--no-pager", ...args], {
    cwd,
    encoding: "utf8",
    shell: false,
    stdio: ["ignore", "pipe", "pipe"],
    env: { ...process.env, GIT_TERMINAL_PROMPT: "0", GIT_EDITOR: "true" },
  });
  if (res.status !== 0) {
    throw new Error(`git ${args.join(" ")} failed: ${(res.stderr || res.stdout || "").trim()}`);
  }
}

const README = `# demo-shop

The target app for PatchPilot's live demo: a small Express shop with **ten planted bugs**
and its happy-path tests, plus the PatchPilot capture middleware in \`sdk/\`.

It is intentionally **buggy** — that is the point. PatchPilot is meant to find and fix
these bugs for real, on its own branch, and open a draft pull request.

\`\`\`bash
npm ci        # only needed for the server (express); the tests need nothing
npm test      # 14 happy-path tests — these pass with the bugs present
npm start     # http://localhost:5050, reporting crashes to PATCHPILOT_ENDPOINT
\`\`\`

Set \`PATCHPILOT_ENDPOINT\` to your PatchPilot server (default
\`http://localhost:4747/api/incidents\`) and \`PATCHPILOT_REPO=demo-shop\`.

Generated by \`npm run demo:make-shop\` in the PatchPilot repository.
`;
export function makeShop(parentDir: string): string {
  const shop = path.join(parentDir, SHOP_NAME);
  if (fs.existsSync(shop)) {
    throw new Error(
      `refusing to overwrite an existing ${shop}\n` +
        `Delete or rename it yourself if you really mean to rebuild it.`
    );
  }

  // 1. the app itself (package.json, server.js, src/lib, tests)
  copyTree(path.join(PROJECT_ROOT, "demo-app"), shop);

  // 2. the middleware, bundled beside the app instead of one level up
  fs.mkdirSync(path.join(shop, "sdk"), { recursive: true });
  fs.copyFileSync(
    path.join(PROJECT_ROOT, "sdk", "patchpilot-express.js"),
    path.join(shop, "sdk", "patchpilot-express.js")
  );

  // 3. repoint the import and the default repo tag
  const serverFile = path.join(shop, "server.js");
  const before = fs.readFileSync(serverFile, "utf8");
  const after = before
    .replace('from "../sdk/patchpilot-express.js"', 'from "./sdk/patchpilot-express.js"')
    .replace(
      'process.env.PATCHPILOT_REPO || process.env.DEMO_REPO || "demo-app"',
      'process.env.PATCHPILOT_REPO || process.env.DEMO_REPO || "demo-shop"'
    );
  if (after === before) {
    throw new Error(
      "demo-app/server.js no longer matches what makeShop rewrites; update this script"
    );
  }
  fs.writeFileSync(serverFile, after, "utf8");

  // 4. identity and housekeeping files
  const pkg = JSON.parse(fs.readFileSync(path.join(shop, "package.json"), "utf8")) as Record<
    string,
    unknown
  >;
  pkg.name = SHOP_NAME;
  pkg.description =
    "Demo shop with planted bugs: the target app PatchPilot fixes in the live demo.";
  fs.writeFileSync(path.join(shop, "package.json"), `${JSON.stringify(pkg, null, 2)}\n`, "utf8");

  fs.writeFileSync(path.join(shop, "README.md"), README, "utf8");
  fs.writeFileSync(path.join(shop, ".gitignore"), "node_modules/\n*.log\n.env\n", "utf8");
  // LF is forced on checkout too (trap 1): exact-text edits must match exactly.
  fs.writeFileSync(path.join(shop, ".gitattributes"), "* text=auto eol=lf\n", "utf8");

  // 5. its own repository, so PatchPilot can push a branch and open a PR against it
  git(shop, ["init", "-b", "main"]);
  git(shop, ["add", "-A"]);
  git(shop, [
    "-c",
    "user.name=PatchPilot",
    "-c",
    "user.email=patchpilot@example.invalid",
    "-c",
    "commit.gpgsign=false",
    "commit",
    "-m",
    "demo-shop: Express shop with ten planted bugs and PatchPilot capture middleware",
  ]);

  return shop;
}

function main(): void {
  const parent = process.argv[2]
    ? path.resolve(process.argv[2])
    : path.resolve(PROJECT_ROOT, "..");
  try {
    const shop = makeShop(parent);
    console.log(`created ${shop}`);
    console.log("");
    console.log("next:");
    console.log(`  cd ${shop}`);
    console.log("  npm ci                       # only the server needs this (express)");
    console.log("  gh repo create <owner>/demo-shop --private --source . --remote origin --push");
    console.log("  # then, in the PatchPilot folder:  npm run demo:shop");
  } catch (err) {
    console.error(`make-shop failed: ${err instanceof Error ? err.message : String(err)}`);
    process.exitCode = 1;
  }
}

// Trap 7: the ESM entry-point check is always false on Windows unless you use pathToFileURL.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}